/**
 * Labels del admin que el cliente resuelve por nombre.
 *
 * Antes esto eran 166 métodos de una línea en el objeto Alpine (`themeTitle()
 * { return this.i18n?.theme?.title || 'Tema'; }`) más un literal anidado en el
 * `define:vars` que repetía la misma estructura. Ahora es una tabla:
 * nombre -> [clave del catálogo, texto en español].
 *
 * El servidor la usa para emitir sólo los textos traducidos; el cliente, para
 * generar los helpers y para `l(nombre)`. Agregar un label es agregar una
 * fila acá.
 */
export const ADMIN_LABELS: Record<string, readonly [string, string]> = {
  // Textos que se usan desde métodos con lógica (plantillas con {n}, mensajes
  // de toast, estados vacíos), no desde un helper de una línea.
  iconPickerFeatureOff: [
    'admin.iconPicker.emptyFeatureOff',
    'Los íconos provienen de packs instalables. Activá la feature "Icon Packs" en Avanzado → Features para habilitarlos.',
  ],
  iconPickerNoPacks: [
    'admin.iconPicker.emptyNoPacks',
    'No hay íconos instalados. Descargá un pack desde la pestaña Íconos Git (Lucide, Simple Icons, etc.).',
  ],
  iconPickerGoFeatures: ['admin.iconPicker.goFeatures', 'Ir a Features'],
  iconPickerGoIconPacks: ['admin.iconPicker.goIconPacks', 'Ir a Íconos Git'],
  layoutGridAlignLeft: ['admin.layout.gridAlign.left', 'Izquierda'],
  layoutGridAlignCenter: ['admin.layout.gridAlign.center', 'Centrado'],
  cardSpanSingle: ['admin.card.spanSingle', '1 columna'],
  cardSpanMultiple: ['admin.card.spanMultiple', '{n} columnas'],
  cardSpanHint: ['admin.card.spanHint', 'Con {cols} columnas en desktop ocupará {n}.'],
  toastSaved: ['admin.dashboard.saved', 'Configuración guardada'],
  toastSavedClamped: [
    'admin.dashboard.savedClamped',
    'Configuración guardada ({n} descripción(es) truncada(s) a 200 chars)',
  ],
  toastReloaded: ['admin.dashboard.reloaded', 'Recargado'],
  toastError: ['admin.dashboard.error', 'Error: {message}'],
  helpTooltip: ['admin.help.tooltip', '¿Qué hace esto?'],
  themePresetApplied: ['admin.theme.preset.applied', 'Preset aplicado'],
  themePresetSaved: ['admin.theme.preset.saved', 'Preset guardado'],
  themeExported: ['admin.theme.advanced.exported', 'Tema exportado'],
  themeImported: ['admin.theme.advanced.imported', 'Tema importado'],
  themeContrastPass: ['admin.theme.colors.contrastPass', 'AA ✓'],
  themeContrastFail: ['admin.theme.colors.contrastFail', 'Bajo contraste'],

  markdownLabel: ['admin.card.markdown', 'Markdown'],
  refreshPreviewLabel: ['admin.card.refreshPreview', 'Refresh preview'],
  previewLabel: ['admin.card.previewLabel', 'Preview'],
  dirtyLabel: ['admin.dashboard.dirty', '● Cambios sin guardar'],
  reloadLabel: ['admin.dashboard.reload', 'Recargar'],
  saveLabel: ['admin.dashboard.save', 'Guardar cambios'],
  savingLabel: ['admin.dashboard.saving', 'Guardando…'],
  tabBranding: ['admin.tab.branding', 'Branding'],
  tabTheme: ['admin.tab.theme', 'Tema'],
  tabLayout: ['admin.tab.layout', 'Layout'],
  layoutTitle: ['admin.layout.title', 'Layout'],
  layoutSectionGrid: ['admin.layout.section.grid', 'Grilla'],
  layoutSectionCards: ['admin.layout.section.cards', 'Tarjetas'],
  layoutSectionBehavior: ['admin.layout.section.behavior', 'Comportamiento'],
  layoutBreakpointDesktop: ['admin.layout.breakpoint.desktop', 'Desktop'],
  layoutBreakpointTablet: ['admin.layout.breakpoint.tablet', 'Tablet'],
  layoutBreakpointMobile: ['admin.layout.breakpoint.mobile', 'Mobile'],
  layoutColumnsDesktopLabel: ['admin.layout.columnsDesktop', 'Columnas desktop'],
  layoutColumnsTabletLabel: ['admin.layout.columnsTablet', 'Columnas tablet'],
  layoutColumnsMobileLabel: ['admin.layout.columnsMobile', 'Columnas mobile'],
  layoutGapLabel: ['admin.layout.gap', 'Espaciado entre tarjetas'],
  layoutCategoryGapLabel: ['admin.layout.categoryGap', 'Espaciado entre categorías'],
  layoutGhostCategoryGapLabel: ['admin.layout.ghostCategoryGap', 'Espaciado de tarjetas sueltas'],
  layoutMaxWidthLabel: ['admin.layout.maxWidth', 'Ancho máximo del contenido'],
  layoutGridAlignLabel: ['admin.layout.gridAlign', 'Alineación del contenido'],
  layoutCardSizeLabel: ['admin.layout.cardSize', 'Tamaño de tarjeta'],
  layoutCardRadiusLabel: ['admin.layout.cardRadius', 'Radio de esquinas'],
  layoutShowDescriptionsLabel: ['admin.layout.showDescriptions', 'Mostrar descripciones'],
  layoutCompactLabel: ['admin.layout.compact', 'Modo compacto'],
  layoutHealthCheckLabel: ['admin.layout.healthCheckInterval', 'Intervalo health check (segundos)'],
  layoutHealthCheckHint: ['admin.layout.healthCheckHint', 'Cada cuánto se vuelve a probar las tarjetas con health check activado. Mín 10s, máx 1h.'],
  layoutPreviewLabel: ['admin.layout.preview.title', 'Vista previa'],
  layoutPreviewMobile: ['admin.layout.preview.mobile', 'Móvil'],
  layoutPreviewTablet: ['admin.layout.preview.tablet', 'Tablet'],
  layoutPreviewDesktop: ['admin.layout.preview.desktop', 'Desktop'],
  cardsFilterPlaceholder: ['admin.cards.filterPlaceholder', 'Filtrar tarjetas…'],
  cardsNewLabel: ['admin.cards.new', 'Nueva tarjeta'],
  cardsFromPresetLabel: ['admin.cards.fromPreset', 'Desde plantilla'],
  cardsFilterDragDisabled: ['admin.cards.filterDragDisabled', 'Con filtro activo el arrastre está deshabilitado. Usá el selector de categoría para mover tarjetas.'],
  cardsOrphanGroupLabel: ['admin.cards.orphanGroup', 'Sin categoría'],
  cardsUngroupedGroupLabel: ['admin.cards.ungroupedGroup', 'Sin grupo'],
  cardsUngroupedGapLabel: ['admin.cards.ungroupedGap', 'Soltá acá para dejar la tarjeta sin grupo'],
  cardsNoteBadgeLabel: ['admin.cards.noteBadge', 'Nota'],
  cardsExpandGroupLabel: ['admin.cards.expandGroup', 'Expandir grupo'],
  cardsCollapseGroupLabel: ['admin.cards.collapseGroup', 'Colapsar grupo'],
  cardsAddToGroupLabel: ['admin.cards.addToGroup', 'Agregar'],
  cardsDragHandleLabel: ['admin.cards.dragHandle', 'Arrastrar para reordenar'],
  cardSpanLabel: ['admin.card.span', 'Ancho (columnas)'],
  cardsUntitledLabel: ['admin.cards.untitled', '(sin título)'],
  cardsCategorySelectLabel: ['admin.cards.categorySelect', 'Categoría'],
  cardsEnabledLabel: ['admin.cards.enabled', 'Activa'],
  cardsEditLabel: ['admin.cards.edit', 'Editar'],
  cardsDeleteLabel: ['admin.cards.delete', 'Borrar tarjeta'],
  cardsSystemBadgeLabel: ['admin.cards.systemBadge', '🔒 Sistema'],
  cardsSystemBadgeTitle: ['admin.cards.systemBadgeTitle', 'Tarjeta del sistema — no se puede editar ni borrar.'],
  cardsGroupEmptyLabel: ['admin.cards.groupEmpty', 'Sin tarjetas en esta categoría. Arrastrá aquí o usá "+ Agregar".'],
  cardsEmptyStateLabel: ['admin.cards.emptyState', 'No hay tarjetas. Agregá la primera con "+ Nueva tarjeta".'],
  tabCategories: ['admin.tab.categories', 'Categorías'],
  tabCards: ['admin.tab.cards', 'Tarjetas'],
  tabAssets: ['admin.tab.assets', 'Assets'],
  tabStatus: ['admin.tab.status', 'Status'],
  tabHardening: ['admin.tab.hardening', 'Hardening'],
  tabPassword: ['admin.tab.password', 'Password'],
  tabAi: ['admin.tab.ai', 'IA'],
  tabWebhooks: ['admin.tab.webhooks', 'Webhooks'],
  tabMaintenance: ['admin.tab.maintenance', 'Mantenimiento'],
  tabAudit: ['admin.tab.audit', 'Auditoría'],
  tabMetrics: ['admin.tab.metrics', 'Métricas'],
  tabOidc: ['admin.tab.oidc', 'OIDC / SSO'],
  tabTokens: ['admin.tab.tokens', 'Tokens API'],
  tabPortals: ['admin.tab.portals', 'Multi-Portal'],
  tabIconPacks: ['admin.tab.iconPacks', 'Íconos Git'],
  tabAdvanced: ['admin.tab.advanced', 'Avanzado'],
  tagsLabel: ['admin.card.tags', 'Tags'],
  tagInputPlaceholder: ['admin.card.tagsPlaceholder', 'agregar tag…'],
  tagsHelp: ['admin.card.tagsHelp', 'Tags kebab-case. Enter/coma/espacio para agregar. Backspace borra el último.'],
  tagsAddLabel: ['admin.card.tagsAdd', '+ agregar'],
  pinnedLabel: ['admin.card.pinned', 'Fijada'],
  featuresTitle: ['admin.features.title', 'Features'],
  featuresIntro: ['admin.features.intro', 'Lista de features opt-in. Activalas segun necesidad.'],
  themeTitle: ['admin.theme.title', 'Tema'],
  themeSectionPresets: ['admin.theme.section.presets', 'Presets'],
  themeSectionBackground: ['admin.theme.section.background', 'Fondo'],
  themeSectionColors: ['admin.theme.section.colors', 'Colores'],
  themeSectionTypography: ['admin.theme.section.typography', 'Tipografía'],
  themeSectionCards: ['admin.theme.section.cards', 'Tarjetas'],
  themeSectionWidgets: ['admin.theme.section.widgets', 'Widgets'],
  themeSectionAnimations: ['admin.theme.section.animations', 'Animaciones'],
  themeSectionAdvanced: ['admin.theme.section.advanced', 'Avanzado'],
  themePresetsIntro: ['admin.theme.presets.intro', 'Elegí un punto de partida.'],
  themeSaveCustomPreset: ['admin.theme.preset.saveCustom', 'Guardar como preset'],
  themeResetDefaults: ['admin.theme.preset.reset', 'Restaurar defaults'],
  themePreviewLabel: ['admin.theme.preview.title', 'Vista previa'],
  themeOpenPreviewTabLabel: ['admin.theme.preview.openTab', 'Abrir preview en pestaña'],
  themeGradientBuilderLabel: ['admin.theme.background.gradientBuilder', 'Constructor de gradiente'],
  themeAdvancedCssLabel: ['admin.theme.background.advancedCss', 'CSS avanzado'],
  themeWidgetsIntro: ['admin.theme.widgets.intro', 'Widgets opcionales del header/pie.'],
  themeAdvancedIntro: ['admin.theme.advanced.intro', 'Override de design tokens.'],
  themeAnimationsIntro: ['admin.theme.animations.intro', 'Todo arranca sin animación: elegí un efecto y recién ahí cambia algo.'],
  themeCardEntranceLabel: ['admin.theme.animations.cardEntrance', 'Entrada de las tarjetas'],
  themeCardEntranceDurationLabel: ['admin.theme.animations.cardEntranceDuration', 'Duración'],
  themeCardEntranceStaggerLabel: ['admin.theme.animations.cardEntranceStagger', 'Retardo entre tarjetas'],
  themeAnimationsGroupEntrance: ['admin.theme.animations.groupEntrance', 'Entrada'],
  themeAnimationsGroupHover: ['admin.theme.animations.groupHover', 'Al pasar el mouse'],
  themeAnimationsGroupText: ['admin.theme.animations.groupText', 'Texto y números'],
  themeAnimationsGroupA11y: ['admin.theme.animations.groupA11y', 'Accesibilidad'],
  themeAnimationsBadgeOnLabel: ['admin.theme.animations.badgeOn', 'activo'],
  themeAnimationsReplayLabel: ['admin.theme.animations.replay', 'Repetir en la vista previa'],
  themeAnimationsResetLabel: ['admin.theme.animations.reset', 'Apagar todo'],
  themeAnimationsScrollNote: ['admin.theme.animations.scrollNote', 'La vista previa siempre muestra la entrada al cargar: en la miniatura no hay scroll que la dispare.'],
  themeCategoryEntranceLabel: ['admin.theme.animations.categoryEntrance', 'Entrada de las categorías'],
  themeEntranceEasingLabel: ['admin.theme.animations.entranceEasing', 'Curva del movimiento'],
  themeEntranceTriggerLabel: ['admin.theme.animations.entranceTrigger', 'Cuándo se dispara'],
  themeEntranceDistanceLabel: ['admin.theme.animations.entranceDistance', 'Distancia del desplazamiento'],
  themeCardHoverLabel: ['admin.theme.animations.cardHover', 'Hover de las tarjetas'],
  themeHoverDurationLabel: ['admin.theme.animations.hoverDuration', 'Duración del hover'],
  themeHeaderEffectLabel: ['admin.theme.animations.headerEffect', 'Efecto del header'],
  themeTitleTypewriterLabel: ['admin.theme.animations.titleTypewriter', 'Título con máquina de escribir'],
  themeCountersLabel: ['admin.theme.animations.counters', 'Contadores animados'],
  themeRespectReducedMotionLabel: ['admin.theme.animations.respectReducedMotion', 'Respetar «reducir movimiento» del sistema'],
  themeDeriveAccentLabel: ['admin.theme.advanced.deriveAccent', 'Derivar del acento'],
  themeResetSurfacesLabel: ['admin.theme.advanced.resetSurfaces', 'Reset superficies'],
  themeResetBordersLabel: ['admin.theme.advanced.resetBorders', 'Reset bordes'],
  themeExportLabel: ['admin.theme.advanced.export', 'Exportar tema'],
  themeImportLabel: ['admin.theme.advanced.import', 'Importar tema'],
  themeTokenSearchPlaceholder: ['admin.theme.advanced.tokenSearch', 'Buscar token…'],
  themeBgTypeLabel: ['admin.theme.background.type', 'Tipo de fondo'],
  themeBgImageLabel: ['admin.theme.background.image', 'Imagen de fondo'],
  themeBgColorLabel: ['admin.theme.background.color', 'Color'],
  themeBgCssLabel: ['admin.theme.background.advancedCss', 'CSS (gradient/color)'],
  themeBlurLabel: ['admin.theme.background.blur', 'Blur'],
  themeOverlayLabel: ['admin.theme.background.overlay', 'Overlay'],
  themeOverlayColorLabel: ['admin.theme.background.overlayColor', 'Color overlay'],
  themeGradientAngleLabel: ['admin.theme.background.angle', 'Ángulo'],
  themeAccentLabel: ['admin.theme.colors.accent', 'Color de acento'],
  themeTextLabel: ['admin.theme.colors.text', 'Color de texto'],
  themeColorModeLabel: ['admin.theme.colors.mode', 'Modo de color'],
  themeAutoStrategyLabel: ['admin.theme.colors.autoStrategy', 'Estrategia auto'],
  themePalettePreviewLabel: ['admin.theme.colors.palettePreview', 'Paleta derivada'],
  themeFontLabel: ['admin.theme.typography.font', 'Tipografía'],
  themeFontWeightLabel: ['admin.theme.typography.weight', 'Peso'],
  themeGoogleFontsLabel: ['admin.theme.typography.googleFonts', 'Google Fonts'],
  themeTypeSampleTitle: ['admin.theme.typography.sampleTitle', 'Título de ejemplo'],
  themeTypeSampleBody: ['admin.theme.typography.sampleBody', 'Texto de cuerpo.'],
  themeTypeSampleCaption: ['admin.theme.typography.sampleCaption', 'Caption'],
  themeCardStyleLabel: ['admin.theme.cards.style', 'Estilo de tarjeta'],
  themeCardBlurLabel: ['admin.theme.cards.blur', 'Blur glass'],
  themeCardBorderLabel: ['admin.theme.cards.border', 'Ancho borde'],
  themeGroupLayoutLabel: ['admin.theme.cards.groupLayout', 'Disposición de grupos'],
  themeShowClockLabel: ['admin.theme.widgets.clock', 'Mostrar reloj'],
  themeShowRefreshLabel: ['admin.theme.widgets.refresh', 'Mostrar refresh'],
  themeShowStatusBarLabel: ['admin.theme.widgets.statusBar', 'Status bar'],
  themeShowModeToggleLabel: ['admin.theme.widgets.modeToggle', 'Toggle claro/oscuro'],
  themeClockPositionLabel: ['admin.theme.widgets.clockPosition', 'Posición reloj'],
  themeClockFormatLabel: ['admin.theme.widgets.clockFormat', 'Formato reloj'],
  themeHeaderOpacityLabel: ['admin.theme.widgets.headerOpacity', 'Opacidad header'],
  themeFooterOpacityLabel: ['admin.theme.widgets.footerOpacity', 'Opacidad footer'],
  themeRadiusLabel: ['admin.theme.advanced.radius', 'Radio base'],
  themeShadowIntensityLabel: ['admin.theme.advanced.shadowIntensity', 'Sombras'],
  themeBgModeDarkLabel: ['admin.theme.background.modeDark', 'Modo oscuro'],
  themeBgModeLightLabel: ['admin.theme.background.modeLight', 'Modo claro'],
  themeBgCopyOtherLabel: ['admin.theme.background.copyOther', 'Copiar del otro modo'],
  themeIconTintLabel: ['admin.theme.colors.iconTint', 'Tinte de iconos'],
  themeIconCustomLabel: ['admin.theme.colors.iconCustom', 'Color de icono'],
  themeTextRampTitle: ['admin.theme.colors.textRamp', 'Rampa de texto por modo'],
  themeTextColorLegacyHint: [
    'admin.theme.colors.textLegacyHint',
    'El campo legacy textColor del JSON se asigna automáticamente al modo que corresponda por luminancia.',
  ],
};

export type AdminLabelName = keyof typeof ADMIN_LABELS;
