export interface AppPreset {
  id: string;
  name: string;
  category: string;
  icon: string;
  color: string;
  description: string;
  defaultCategoryName?: string;
}

export const APP_PRESETS: ReadonlyArray<AppPreset> = [
  // ── Inteligencia Artificial & LLMs (Web UIs & Servidores) ─────────────────
  {
    id: 'openwebui',
    name: 'Open WebUI',
    category: 'ai',
    icon: 'sparkles',
    color: '#10b981',
    description: 'Interfaz web avanzada tipo ChatGPT con soporte RAG, chat con documentos y Ollama.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'librechat',
    name: 'LibreChat',
    category: 'ai',
    icon: 'chat',
    color: '#6366f1',
    description: 'Plataforma web unificada de chat multi-modelo compatible con OpenAI, Anthropic, Ollama y plugins.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'nextchat',
    name: 'NextChat',
    category: 'ai',
    icon: 'chat',
    color: '#06b6d4',
    description: 'Cliente web ligero y ultra-rápido para interactuar con modelos de IA (ChatGPT-Next-Web).',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'lobechat',
    name: 'Lobe Chat',
    category: 'ai',
    icon: 'sparkles',
    color: '#ec4899',
    description: 'Plataforma web de chat con diseño moderno, soporte multi-modal, plugins y mercado de agentes.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'anythingllm',
    name: 'AnythingLLM',
    category: 'ai',
    icon: 'file-text',
    color: '#3b82f6',
    description: 'Solución web todo-en-uno de RAG privado para chatear con documentos y bases de conocimiento.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'ragflow',
    name: 'RAGFlow',
    category: 'ai',
    icon: 'file-text',
    color: '#155eef',
    description: 'Motor RAG de última generación con comprensión profunda de documentos y orquestación web.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'ollama',
    name: 'Ollama Server',
    category: 'ai',
    icon: 'bot',
    color: '#ffffff',
    description: 'Servidor y endpoint web local de inferencia de modelos LLM (Llama, Qwen, DeepSeek, Mistral).',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'llamacpp',
    name: 'llama.cpp Server',
    category: 'ai',
    icon: 'cpu',
    color: '#e55039',
    description: 'Servidor web e interfaz de inferencia C++ para cuantizaciones GGUF en CPU/GPU.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'vllm',
    name: 'vLLM Server',
    category: 'ai',
    icon: 'zap',
    color: '#8b5cf6',
    description: 'Servidor de inferencia de alto rendimiento con endpoint compatible OpenAI y métricas web.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'tgi',
    name: 'Text Generation Inference (TGI)',
    category: 'ai',
    icon: 'server',
    color: '#ff9900',
    description: 'Servidor de Hugging Face para despliegue y producción de LLMs a gran escala.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'localai',
    name: 'LocalAI',
    category: 'ai',
    icon: 'bot',
    color: '#00b894',
    description: 'Servidor web drop-in compatible con OpenAI API para texto, voz, embeddings y visión.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'oobabooga',
    name: 'Text Generation WebUI',
    category: 'ai',
    icon: 'terminal',
    color: '#0984e3',
    description: 'Interfaz web para entusiastas con control granular de parámetros y múltiples loaders.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'dify',
    name: 'Dify Studio',
    category: 'ai',
    icon: 'layers',
    color: '#155eef',
    description: 'Plataforma web completa para orquestación de agentes, RAG y desarrollo de aplicaciones LLM.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'flowise',
    name: 'Flowise',
    category: 'ai',
    icon: 'layers',
    color: '#4f46e5',
    description: 'Constructor visual drag-and-drop en navegador de pipelines LangChain y flujos de agentes.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'langflow',
    name: 'Langflow',
    category: 'ai',
    icon: 'layers',
    color: '#7c3aed',
    description: 'Interfaz web visual para construir, probar e integrar flujos multi-agente y RAG.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'litellm',
    name: 'LiteLLM Admin Dashboard',
    category: 'ai',
    icon: 'globe',
    color: '#06b6d4',
    description: 'Panel web de administración, balanceo de carga y proxy para unificar 100+ LLMs.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'langfuse',
    name: 'Langfuse',
    category: 'ai',
    icon: 'bar-chart-2',
    color: '#ec4899',
    description: 'Dashboard web de observabilidad, trazas, costos, latencia y evaluación de aplicaciones LLM.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'searxng',
    name: 'SearXNG',
    category: 'ai',
    icon: 'search',
    color: '#3b82f6',
    description: 'Metabuscador web privado para dotar a tus agentes de IA de acceso a internet en tiempo real.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'comfyui',
    name: 'ComfyUI',
    category: 'ai',
    icon: 'image',
    color: '#f59e0b',
    description: 'Entorno visual web basado en nodos para generación de imágenes con Stable Diffusion y Flux.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'fooocus',
    name: 'Fooocus',
    category: 'ai',
    icon: 'image',
    color: '#10b981',
    description: 'Generador de imágenes web fácil de usar inspirado en Midjourney y basado en SDXL.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'whisper',
    name: 'Whisper WebUI',
    category: 'ai',
    icon: 'mic',
    color: '#14b8a6',
    description: 'Interfaz web para transcripción de audio y voz a texto con modelos Whisper.',
    defaultCategoryName: 'Inteligencia Artificial',
  },
  {
    id: 'kokoro',
    name: 'Kokoro TTS Web',
    category: 'ai',
    icon: 'mic',
    color: '#f43f5e',
    description: 'Servidor web para síntesis de voz a texto (TTS) ligero, ultra-rápido y con calidad natural.',
    defaultCategoryName: 'Inteligencia Artificial',
  },

  // ── Agentes Autónomos & Frameworks Multi-Agente (Con Web UI) ─────────────
  {
    id: 'autogen',
    name: 'AutoGen Studio',
    category: 'ai-agents',
    icon: 'users',
    color: '#0078d4',
    description: 'Plataforma web de Microsoft para diseñar, probar y desplegar equipos multi-agente colaborativos.',
    defaultCategoryName: 'Agentes & IA',
  },
  {
    id: 'langgraph',
    name: 'LangGraph Studio',
    category: 'ai-agents',
    icon: 'layers',
    color: '#22c55e',
    description: 'Entorno web interactivo para orquestar y visualizar agentes cíclicos con estado y memoria.',
    defaultCategoryName: 'Agentes & IA',
  },
  {
    id: 'openhands',
    name: 'OpenHands',
    category: 'ai-agents',
    icon: 'code',
    color: '#2563eb',
    description: 'Plataforma web autónoma de desarrollo de software para escribir código, ejecutar tests y resolver issues.',
    defaultCategoryName: 'Agentes & IA',
  },
  {
    id: 'devika',
    name: 'Devika AI',
    category: 'ai-agents',
    icon: 'code',
    color: '#3b82f6',
    description: 'Ingeniero de software autónomo con panel web, terminal integrada y visor de navegación.',
    defaultCategoryName: 'Agentes & IA',
  },
  {
    id: 'boltdiy',
    name: 'Bolt.diy',
    category: 'ai-agents',
    icon: 'zap',
    color: '#ff6b00',
    description: 'Entorno web autónomo para crear, previsualizar y desplegar aplicaciones web con agentes de IA.',
    defaultCategoryName: 'Agentes & IA',
  },
  {
    id: 'autogpt',
    name: 'AutoGPT Web',
    category: 'ai-agents',
    icon: 'zap',
    color: '#3b82f6',
    description: 'Plataforma web para construir y ejecutar agentes autónomos que descomponen metas en tareas.',
    defaultCategoryName: 'Agentes & IA',
  },
  {
    id: 'agentgpt',
    name: 'AgentGPT',
    category: 'ai-agents',
    icon: 'bot',
    color: '#3b82f6',
    description: 'Interfaz web para configurar y desplegar agentes autónomos directamente en el navegador.',
    defaultCategoryName: 'Agentes & IA',
  },
  {
    id: 'superagi',
    name: 'SuperAGI',
    category: 'ai-agents',
    icon: 'bot',
    color: '#f43f5e',
    description: 'Plataforma web enterprise para construir, gestionar y ejecutar agentes autónomos concurrentes.',
    defaultCategoryName: 'Agentes & IA',
  },
  {
    id: 'taskingai',
    name: 'TaskingAI',
    category: 'ai-agents',
    icon: 'layers',
    color: '#4f46e5',
    description: 'Plataforma web integral para desarrollo y ejecución de agentes autónomos con plugins y RAG.',
    defaultCategoryName: 'Agentes & IA',
  },
  {
    id: 'chatdev',
    name: 'ChatDev Visualizer',
    category: 'ai-agents',
    icon: 'users',
    color: '#f97316',
    description: 'Visualizador web para simular empresas de software autónomas con agentes (CEO, CTO, Dev, QA).',
    defaultCategoryName: 'Agentes & IA',
  },
  {
    id: 'gpt-researcher',
    name: 'GPT Researcher Web',
    category: 'ai-agents',
    icon: 'search',
    color: '#10b981',
    description: 'Interfaz web para agente autónomo de investigación profunda en la web con reportes detallados.',
    defaultCategoryName: 'Agentes & IA',
  },
  {
    id: 'browser-use',
    name: 'Browser-Use Web UI',
    category: 'ai-agents',
    icon: 'globe',
    color: '#6366f1',
    description: 'Panel web para automatización y navegación autónoma en sitios web con visión y LLMs.',
    defaultCategoryName: 'Agentes & IA',
  },
  {
    id: 'khoj',
    name: 'Khoj Web',
    category: 'ai-agents',
    icon: 'book-open',
    color: '#ec4899',
    description: 'Segundo cerebro y asistente de IA privado accesible por web para buscar en tus notas y documentos.',
    defaultCategoryName: 'Agentes & IA',
  },
  {
    id: 'qdrant',
    name: 'Qdrant Web Dashboard',
    category: 'ai-agents',
    icon: 'database',
    color: '#dc2626',
    description: 'Panel web interactivo para base de datos vectorial de alto rendimiento para memoria y embeddings de IA.',
    defaultCategoryName: 'Agentes & IA',
  },
  {
    id: 'chroma',
    name: 'Chroma Explorer',
    category: 'ai-agents',
    icon: 'database',
    color: '#8b5cf6',
    description: 'Dashboard web para explorar colecciones, documentos y embeddings en bases de datos vectoriales Chroma.',
    defaultCategoryName: 'Agentes & IA',
  },
  {
    id: 'aider',
    name: 'Aider Web Companion',
    category: 'ai-agents',
    icon: 'terminal',
    color: '#a855f7',
    description: 'Interfaz web complementaria para programar en pareja con IA y control de versiones Git.',
    defaultCategoryName: 'Agentes & IA',
  },

  // ── ERP, CRM & Gestión Empresarial (Sistemas de Negocio) ─────────────────
  {
    id: 'odoo',
    name: 'Odoo ERP & CRM',
    category: 'business',
    icon: 'briefcase',
    color: '#714b67',
    description: 'Suite empresarial todo-en-uno de código abierto: ERP, CRM, Facturación, Inventario, Punto de Venta y RRHH.',
    defaultCategoryName: 'Negocios & ERP',
  },
  {
    id: 'erpnext',
    name: 'ERPNext',
    category: 'business',
    icon: 'briefcase',
    color: '#0089ff',
    description: 'Sistema ERP open-source completo para manufactura, compras, ventas, contabilidad y gestión de proyectos.',
    defaultCategoryName: 'Negocios & ERP',
  },
  {
    id: 'dolibarr',
    name: 'Dolibarr ERP / CRM',
    category: 'business',
    icon: 'briefcase',
    color: '#2980b9',
    description: 'Software ERP y CRM modular y fácil de usar para pequeñas y medianas empresas, autónomos y fundaciones.',
    defaultCategoryName: 'Negocios & ERP',
  },
  {
    id: 'twenty',
    name: 'Twenty CRM',
    category: 'business',
    icon: 'users',
    color: '#10b981',
    description: 'Plataforma CRM moderna, colaborativa y de código abierto (alternativa ágil a HubSpot y Salesforce).',
    defaultCategoryName: 'Negocios & ERP',
  },
  {
    id: 'espocrm',
    name: 'EspoCRM',
    category: 'business',
    icon: 'users',
    color: '#27ae60',
    description: 'Sistema CRM web ligero, rápido y altamente personalizable para gestión de ventas y clientes.',
    defaultCategoryName: 'Negocios & ERP',
  },
  {
    id: 'suitecrm',
    name: 'SuiteCRM',
    category: 'business',
    icon: 'users',
    color: '#e67e22',
    description: 'Solución CRM empresarial de grado enterprise con flujos de trabajo avanzados y reportes detallados.',
    defaultCategoryName: 'Negocios & ERP',
  },
  {
    id: 'invoiceninja',
    name: 'Invoice Ninja',
    category: 'business',
    icon: 'credit-card',
    color: '#1363df',
    description: 'Plataforma web de facturación profesional, cotizaciones, gastos y cobros en línea para empresas y freelancers.',
    defaultCategoryName: 'Negocios & ERP',
  },
  {
    id: 'akaunting',
    name: 'Akaunting',
    category: 'business',
    icon: 'dollar-sign',
    color: '#5552b9',
    description: 'Software de contabilidad web gratuito y autohospedado para pequeñas empresas y profesionales.',
    defaultCategoryName: 'Negocios & ERP',
  },
  {
    id: 'btcpay',
    name: 'BTCPay Server',
    category: 'business',
    icon: 'dollar-sign',
    color: '#51b13e',
    description: 'Procesador web de pagos en Bitcoin y criptomonedas autohospedado, sin comisiones ni intermediarios.',
    defaultCategoryName: 'Negocios & ERP',
  },

  // ── Atención al Cliente & Helpdesk (Mesas de Ayuda) ──────────────────────
  {
    id: 'chatwoot',
    name: 'Chatwoot',
    category: 'support',
    icon: 'chat',
    color: '#1f93ff',
    description: 'Plataforma omnicanal de soporte al cliente, chat en vivo y bandeja de entrada compartida (alt a Intercom).',
    defaultCategoryName: 'Soporte & Helpdesk',
  },
  {
    id: 'zammad',
    name: 'Zammad Helpdesk',
    category: 'support',
    icon: 'message-square',
    color: '#334155',
    description: 'Sistema web de ticketing y mesa de ayuda para soporte técnico con integración de correo, chat y teléfono.',
    defaultCategoryName: 'Soporte & Helpdesk',
  },
  {
    id: 'freescout',
    name: 'FreeScout',
    category: 'support',
    icon: 'mail',
    color: '#10b981',
    description: 'Mesa de ayuda ligera y bandeja de entrada compartida de correo (alternativa a Zendesk / Help Scout).',
    defaultCategoryName: 'Soporte & Helpdesk',
  },
  {
    id: 'osticket',
    name: 'osTicket',
    category: 'support',
    icon: 'file-text',
    color: '#e55039',
    description: 'Sistema web de tickets de soporte técnico de código abierto confiable y altamente personalizable.',
    defaultCategoryName: 'Soporte & Helpdesk',
  },

  // ── Analítica Web, Producto & Marketing (Dashboards) ─────────────────────
  {
    id: 'umami',
    name: 'Umami Analytics',
    category: 'analytics',
    icon: 'bar-chart',
    color: '#000000',
    description: 'Analítica web privada, moderna, amigable y respetuosa con la privacidad (alternativa a Google Analytics).',
    defaultCategoryName: 'Analítica',
  },
  {
    id: 'plausible',
    name: 'Plausible Analytics',
    category: 'analytics',
    icon: 'bar-chart-2',
    color: '#5850ec',
    description: 'Panel web de analítica web ligero, sin cookies y 100% compatible con normativas de privacidad GDPR/CCPA.',
    defaultCategoryName: 'Analítica',
  },
  {
    id: 'matomo',
    name: 'Matomo Analytics',
    category: 'analytics',
    icon: 'pie-chart',
    color: '#e74c3c',
    description: 'Plataforma líder de analítica web completa, mapas de calor y optimización de conversión con control total de datos.',
    defaultCategoryName: 'Analítica',
  },
  {
    id: 'posthog',
    name: 'PostHog',
    category: 'analytics',
    icon: 'activity',
    color: '#f54e00',
    description: 'Suite completa de analítica de producto, grabación de sesiones, feature flags y funnels de conversión.',
    defaultCategoryName: 'Analítica',
  },
  {
    id: 'listmonk',
    name: 'Listmonk',
    category: 'marketing',
    icon: 'mail',
    color: '#0984e3',
    description: 'Gestor web de listas de correo masivo, campañas de email marketing y boletines de noticias de alto rendimiento.',
    defaultCategoryName: 'Marketing',
  },
  {
    id: 'mautic',
    name: 'Mautic',
    category: 'marketing',
    icon: 'zap',
    color: '#4e5d9d',
    description: 'Plataforma de automatización de marketing de código abierto (campañas, nutrición de leads, segmentación).',
    defaultCategoryName: 'Marketing',
  },

  // ── CMS, Blogs & Publicación Web ──────────────────────────────────────────
  {
    id: 'ghost',
    name: 'Ghost CMS',
    category: 'cms',
    icon: 'edit-3',
    color: '#15171a',
    description: 'Plataforma web moderna de publicación de blogs, newsletters y sitios de membresías de suscripción.',
    defaultCategoryName: 'CMS & Blogs',
  },
  {
    id: 'wordpress',
    name: 'WordPress',
    category: 'cms',
    icon: 'globe',
    color: '#21759b',
    description: 'El gestor de contenidos web (CMS) y blogs más popular del mundo, con miles de plugins y temas.',
    defaultCategoryName: 'CMS & Blogs',
  },
  {
    id: 'docmost',
    name: 'Docmost Wiki',
    category: 'documentation',
    icon: 'book-open',
    color: '#2563eb',
    description: 'Plataforma colaborativa de documentación y wiki de conocimiento para equipos (alternativa a Notion / Confluence).',
    defaultCategoryName: 'Documentación',
  },
  {
    id: 'hoarder',
    name: 'Hoarder',
    category: 'productivity',
    icon: 'bookmark',
    color: '#ff6b6b',
    description: 'Gestor web de marcadores e información con captura automática de páginas, OCR y categorización por IA.',
    defaultCategoryName: 'Productividad',
  },
  {
    id: 'freshrss',
    name: 'FreshRSS',
    category: 'productivity',
    icon: 'radio',
    color: '#0078d7',
    description: 'Agregador y lector de feeds RSS/Atom web rápido, potente y con soporte multi-usuario.',
    defaultCategoryName: 'Productividad',
  },

  // ── Bases de Datos & Búsqueda (Consolas Web & Exploradores) ───────────────
  {
    id: 'pgadmin',
    name: 'pgAdmin Web',
    category: 'database',
    icon: 'database',
    color: '#336791',
    description: 'Herramienta web de administración y desarrollo para bases de datos PostgreSQL.',
    defaultCategoryName: 'Bases de Datos',
  },
  {
    id: 'phpmyadmin',
    name: 'phpMyAdmin',
    category: 'database',
    icon: 'database',
    color: '#f39c12',
    description: 'Administración web gráfica para bases de datos MySQL y MariaDB.',
    defaultCategoryName: 'Bases de Datos',
  },
  {
    id: 'adminer',
    name: 'Adminer',
    category: 'database',
    icon: 'database',
    color: '#107c41',
    description: 'Gestor web ultra-liviano todo-en-uno para MySQL, PostgreSQL, SQLite y MS SQL.',
    defaultCategoryName: 'Bases de Datos',
  },
  {
    id: 'cloudbeaver',
    name: 'CloudBeaver',
    category: 'database',
    icon: 'database',
    color: '#3498db',
    description: 'Cliente web universal de bases de datos basado en DBeaver con editor SQL y diagramas ER.',
    defaultCategoryName: 'Bases de Datos',
  },
  {
    id: 'mongoexpress',
    name: 'Mongo Express',
    category: 'database',
    icon: 'database',
    color: '#13aa52',
    description: 'Interfaz gráfica web interactiva para administración de bases de datos MongoDB.',
    defaultCategoryName: 'Bases de Datos',
  },
  {
    id: 'nocodb',
    name: 'NocoDB',
    category: 'database',
    icon: 'database',
    color: '#1890ff',
    description: 'Convierte cualquier base de datos relacional en una hoja de cálculo inteligente tipo Airtable.',
    defaultCategoryName: 'Bases de Datos',
  },
  {
    id: 'baserow',
    name: 'Baserow',
    category: 'database',
    icon: 'database',
    color: '#533be5',
    description: 'Base de datos relacional colaborativa y sin código con interfaz web fluida y APIs instantáneas.',
    defaultCategoryName: 'Bases de Datos',
  },
  {
    id: 'redisinsight',
    name: 'RedisInsight',
    category: 'database',
    icon: 'database',
    color: '#dc382d',
    description: 'Consola web para visualización, análisis y gestión de estructuras de datos en Redis.',
    defaultCategoryName: 'Bases de Datos',
  },
  {
    id: 'neo4j',
    name: 'Neo4j Browser',
    category: 'database',
    icon: 'database',
    color: '#018bff',
    description: 'Interfaz web interactiva para explorar grafos y ejecutar consultas Cypher en Neo4j.',
    defaultCategoryName: 'Bases de Datos',
  },
  {
    id: 'couchdb',
    name: 'CouchDB Fauxton',
    category: 'database',
    icon: 'database',
    color: '#e74c3c',
    description: 'Panel web oficial integrado para bases de datos de documentos Apache CouchDB.',
    defaultCategoryName: 'Bases de Datos',
  },
  {
    id: 'kibana',
    name: 'Kibana / OpenSearch Dashboards',
    category: 'database',
    icon: 'bar-chart',
    color: '#f04b83',
    description: 'Plataforma web de exploración, análisis y visualización de datos para Elasticsearch y OpenSearch.',
    defaultCategoryName: 'Bases de Datos',
  },
  {
    id: 'meilisearch',
    name: 'Meilisearch Dashboard',
    category: 'database',
    icon: 'search',
    color: '#ff5caa',
    description: 'Motor de búsqueda ultrarrápido con interfaz web integrada para pruebas y búsqueda instantánea.',
    defaultCategoryName: 'Bases de Datos',
  },
  {
    id: 'typesense',
    name: 'Typesense Dashboard',
    category: 'database',
    icon: 'search',
    color: '#d63031',
    description: 'Panel web de búsqueda tipotolerante y en memoria de alto rendimiento.',
    defaultCategoryName: 'Bases de Datos',
  },
  {
    id: 'pocketbase',
    name: 'PocketBase Admin',
    category: 'database',
    icon: 'database',
    color: '#e76f51',
    description: 'Panel web de administración para backend SQLite con Auth y base de datos en tiempo real.',
    defaultCategoryName: 'Bases de Datos',
  },
  {
    id: 'supabase',
    name: 'Supabase Studio',
    category: 'database',
    icon: 'database',
    color: '#3ecf8e',
    description: 'Dashboard web de administración para PostgreSQL, Auth, Storage y Edge Functions.',
    defaultCategoryName: 'Bases de Datos',
  },

  // ── Git, Repositorios & CI/CD (Servicios Web Git) ─────────────────────────
  {
    id: 'gitlab',
    name: 'GitLab',
    category: 'development',
    icon: 'git-branch',
    color: '#fc6d26',
    description: 'Plataforma web completa de repositorios git, CI/CD pipelines, seguridad y code review.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'gitea',
    name: 'Gitea / Forgejo',
    category: 'development',
    icon: 'git-commit',
    color: '#609926',
    description: 'Servicio web git ligero autohospedado con soporte para issues, pull requests y CI/CD actions.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'gogs',
    name: 'Gogs',
    category: 'development',
    icon: 'git-branch',
    color: '#e74c3c',
    description: 'Servidor web de repositorios Git autoalojado ultra-liviano, veloz y sin esfuerzo de mantenimiento.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'onedev',
    name: 'OneDev',
    category: 'development',
    icon: 'git-commit',
    color: '#1976d2',
    description: 'Servidor Git todo-en-uno con CI/CD visual, tablero Kanban y navegación inteligente de código.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'sourcehut',
    name: 'SourceHut',
    category: 'development',
    icon: 'code',
    color: '#2c3e50',
    description: 'Suite web modular y minimalista de desarrollo de software libre y alojamiento git.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'development',
    icon: 'github',
    color: '#24292e',
    description: 'Plataforma web líder de desarrollo colaborativo, pull requests y control de versiones.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'jenkins',
    name: 'Jenkins',
    category: 'development',
    icon: 'cpu',
    color: '#d33833',
    description: 'Servidor web de integración continua y delivery automatizado con amplio soporte de plugins.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'woodpecker',
    name: 'Woodpecker CI',
    category: 'development',
    icon: 'cpu',
    color: '#00bcd4',
    description: 'Motor web de CI/CD moderno y modular basado en ejecución de pipelines en contenedores Docker.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'drone',
    name: 'Drone CI',
    category: 'development',
    icon: 'cpu',
    color: '#2c3e50',
    description: 'Plataforma web de entrega e integración continua automatizada con pipelines declarativos en YAML.',
    defaultCategoryName: 'Desarrollo',
  },

  // ── Desarrollo, PaaS & Backends (Plataformas Web) ─────────────────────────
  {
    id: 'coolify',
    name: 'Coolify PaaS',
    category: 'development',
    icon: 'rocket',
    color: '#6366f1',
    description: 'Plataforma PaaS web autohospedada para desplegar apps, bases de datos y servicios con un clic (Heroku/Vercel alt).',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'caprover',
    name: 'CapRover',
    category: 'development',
    icon: 'rocket',
    color: '#0070f3',
    description: 'PaaS web ultra-fácil para desplegar aplicaciones Node, Python, PHP, Ruby y contenedores Docker con SSL.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'appwrite',
    name: 'Appwrite Console',
    category: 'development',
    icon: 'layers',
    color: '#fd366e',
    description: 'Consola web de Backend-as-a-Service (BaaS) seguro con Auth, Databases, Storage y Functions.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'code-server',
    name: 'VS Code Server',
    category: 'development',
    icon: 'code',
    color: '#007acc',
    description: 'Entorno de desarrollo VS Code completo en el navegador web accesible desde cualquier lugar.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'n8n',
    name: 'n8n',
    category: 'automation',
    icon: 'zap',
    color: '#ea4b71',
    description: 'Plataforma web de automatización de flujos de trabajo basada en nodos y conectores.',
    defaultCategoryName: 'Automatización',
  },
  {
    id: 'jupyter',
    name: 'JupyterLab',
    category: 'data',
    icon: 'terminal',
    color: '#f37626',
    description: 'Entorno interactivo web para ciencia de datos, análisis y notebooks.',
    defaultCategoryName: 'Data Science',
  },
  {
    id: 'directus',
    name: 'Directus',
    category: 'development',
    icon: 'layers',
    color: '#6644ff',
    description: 'Panel web de administración y API REST/GraphQL instantánea sobre cualquier base de datos SQL.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'strapi',
    name: 'Strapi',
    category: 'development',
    icon: 'layers',
    color: '#4945ff',
    description: 'Panel web de gestión de contenidos (Headless CMS) líder en Node.js.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'hoppscotch',
    name: 'Hoppscotch',
    category: 'development',
    icon: 'rocket',
    color: '#25c2a0',
    description: 'Cliente web de pruebas de API REST, GraphQL y WebSocket (alternativa a Postman).',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'sonarqube',
    name: 'SonarQube',
    category: 'development',
    icon: 'shield-check',
    color: '#cb333b',
    description: 'Dashboard web de inspección continua de calidad y seguridad estática de código.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'harbor',
    name: 'Harbor Registry',
    category: 'development',
    icon: 'package',
    color: '#4990e2',
    description: 'Portal web de registro de artefactos y contenedores Docker con escaneo de seguridad.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'rundeck',
    name: 'Rundeck',
    category: 'development',
    icon: 'layers',
    color: '#cf262f',
    description: 'Plataforma web de automatización de runbooks y ejecución de tareas programadas en servidores.',
    defaultCategoryName: 'Desarrollo',
  },
  {
    id: 'unleash',
    name: 'Unleash',
    category: 'development',
    icon: 'zap',
    color: '#6c5ce7',
    description: 'Dashboard web de gestión de feature flags y lanzamientos progresivos de funcionalidades.',
    defaultCategoryName: 'Desarrollo',
  },

  // ── SysOps, Servidores & Gestión de Sistema (Paneles Web) ─────────────────
  {
    id: 'cockpit',
    name: 'Cockpit Linux',
    category: 'sysops',
    icon: 'server',
    color: '#0088ce',
    description: 'Panel web oficial de administración de servidores Linux (red, almacenamiento, logs, usuarios, systemd).',
    defaultCategoryName: 'SysOps',
  },
  {
    id: 'webmin',
    name: 'Webmin',
    category: 'sysops',
    icon: 'server',
    color: '#27ae60',
    description: 'Consola web clásica y exhaustiva para configuración y administración profunda de sistemas Unix/Linux.',
    defaultCategoryName: 'SysOps',
  },
  {
    id: 'casaos',
    name: 'CasaOS',
    category: 'sysops',
    icon: 'home',
    color: '#0f52ba',
    description: 'Sistema operativo y panel web elegante con tienda de aplicaciones Docker para servidores caseros.',
    defaultCategoryName: 'SysOps',
  },
  {
    id: 'zimaos',
    name: 'ZimaOS',
    category: 'sysops',
    icon: 'server',
    color: '#10b981',
    description: 'Sistema operativo para computación en el borde y almacenamiento en la nube personal.',
    defaultCategoryName: 'SysOps',
  },
  {
    id: 'umbrel',
    name: 'Umbrel',
    category: 'sysops',
    icon: 'server',
    color: '#4f46e5',
    description: 'Sistema operativo personal con interfaz web limpia y tienda de apps autoalojadas para nodos privados.',
    defaultCategoryName: 'SysOps',
  },
  {
    id: 'scrutiny',
    name: 'Scrutiny',
    category: 'sysops',
    icon: 'activity',
    color: '#f39c12',
    description: 'Panel web de monitoreo de salud SMART y estado de temperatura de discos duros y SSDs.',
    defaultCategoryName: 'SysOps',
  },
  {
    id: 'meshcentral',
    name: 'MeshCentral',
    category: 'sysops',
    icon: 'monitor',
    color: '#2980b9',
    description: 'Servidor web de gestión, soporte y control remoto de escritorios y dispositivos por navegador.',
    defaultCategoryName: 'SysOps',
  },

  // ── Backups & Recuperación ante Desastres (Consolas Web) ───────────────────
  {
    id: 'duplicati',
    name: 'Duplicati',
    category: 'backups',
    icon: 'upload-cloud',
    color: '#007acc',
    description: 'Sistema web de copias de seguridad encriptadas e incrementales con soporte para múltiples nubes y almacenamiento local.',
    defaultCategoryName: 'Backups',
  },
  {
    id: 'kopia',
    name: 'Kopia Web UI',
    category: 'backups',
    icon: 'upload-cloud',
    color: '#20c997',
    description: 'Herramienta de copias de seguridad rápida y segura con deduplicación del lado del cliente, cifrado y consola web.',
    defaultCategoryName: 'Backups',
  },
  {
    id: 'urbackup',
    name: 'UrBackup',
    category: 'backups',
    icon: 'database',
    color: '#e74c3c',
    description: 'Sistema cliente-servidor de copias de seguridad de imágenes de disco y archivos con panel web centralizado.',
    defaultCategoryName: 'Backups',
  },
  {
    id: 'bareos',
    name: 'Bareos WebUI',
    category: 'backups',
    icon: 'database',
    color: '#2c3e50',
    description: 'Consola web enterprise para gestión de copias de seguridad, almacenamiento en cinta y recuperación ante desastres.',
    defaultCategoryName: 'Backups',
  },
  {
    id: 'proxmox-backup',
    name: 'Proxmox Backup Server',
    category: 'backups',
    icon: 'server',
    color: '#e57000',
    description: 'Servidor web de copias de seguridad de nivel empresarial para máquinas virtuales y contenedores Proxmox.',
    defaultCategoryName: 'Backups',
  },

  // ── Virtualización, VMs & Kubernetes (Hipervisores Web) ────────────────────
  {
    id: 'proxmox',
    name: 'Proxmox VE',
    category: 'virtualization',
    icon: 'server',
    color: '#e57000',
    description: 'Panel web de virtualización para máquinas virtuales KVM y contenedores LXC con clustering y HA.',
    defaultCategoryName: 'Virtualización',
  },
  {
    id: 'unraid',
    name: 'Unraid OS',
    category: 'virtualization',
    icon: 'server',
    color: '#f15a24',
    description: 'Sistema operativo NAS con panel web para gestión flexible de discos, máquinas virtuales KVM y Docker.',
    defaultCategoryName: 'Virtualización',
  },
  {
    id: 'xen-orchestra',
    name: 'Xen Orchestra',
    category: 'virtualization',
    icon: 'server',
    color: '#2d3748',
    description: 'Plataforma web completa de administración, copias de seguridad continuas y métricas para hipervisores XCP-ng / Xen.',
    defaultCategoryName: 'Virtualización',
  },
  {
    id: 'harvester',
    name: 'Harvester HCI',
    category: 'virtualization',
    icon: 'layers',
    color: '#0075a8',
    description: 'Plataforma de infraestructura hiperconvergente (HCI) open-source para gestión de VMs y Kubernetes con consola web.',
    defaultCategoryName: 'Virtualización',
  },
  {
    id: 'rancher',
    name: 'Rancher',
    category: 'virtualization',
    icon: 'server',
    color: '#0075a8',
    description: 'Plataforma web empresarial para gestión centralizada multi-cluster de Kubernetes y despliegue de cargas de trabajo.',
    defaultCategoryName: 'Virtualización',
  },
  {
    id: 'kubesphere',
    name: 'KubeSphere',
    category: 'virtualization',
    icon: 'layers',
    color: '#10b981',
    description: 'Consola web y sistema operativo en la nube para orquestación de Kubernetes, DevOps y microservicios.',
    defaultCategoryName: 'Virtualización',
  },
  {
    id: 'kasm',
    name: 'Kasm Workspaces',
    category: 'virtualization',
    icon: 'monitor',
    color: '#0066cc',
    description: 'Plataforma web de streaming de escritorios, aplicaciones y navegadores aislados en contenedores (VDI/Browser Isolation).',
    defaultCategoryName: 'Virtualización',
  },

  // ── Redes, Proxies & VPNs (Consolas Web de Conectividad) ──────────────────
  {
    id: 'opnsense',
    name: 'OPNsense',
    category: 'infrastructure',
    icon: 'shield-check',
    color: '#d94436',
    description: 'Firewall y router enterprise open-source con panel web completo y detección de intrusos (IPS/IDS).',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'pfsense',
    name: 'pfSense',
    category: 'infrastructure',
    icon: 'shield-check',
    color: '#005b94',
    description: 'Distribución de firewall, VPN y enrutamiento con potente interfaz de administración web.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'openwrt',
    name: 'OpenWrt LuCI',
    category: 'infrastructure',
    icon: 'radio',
    color: '#0083ca',
    description: 'Interfaz web gráfica de configuración para routers y puntos de acceso OpenWrt.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'portainer',
    name: 'Portainer',
    category: 'infrastructure',
    icon: 'server',
    color: '#13bef9',
    description: 'Consola web gráfica para gestión de contenedores Docker y clusters Kubernetes.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'dockge',
    name: 'Dockge',
    category: 'infrastructure',
    icon: 'server',
    color: '#0ea5e9',
    description: 'Administrador web reactivo para Docker Compose stacks y gestión de contenedores.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'truenas',
    name: 'TrueNAS',
    category: 'infrastructure',
    icon: 'database',
    color: '#0095d5',
    description: 'Panel web del sistema operativo de almacenamiento en red (NAS) con OpenZFS.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'npm',
    name: 'Nginx Proxy Manager',
    category: 'infrastructure',
    icon: 'globe',
    color: '#009688',
    description: 'Administrador web de proxy inverso con gestión de certificados SSL automáticos.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'traefik',
    name: 'Traefik Dashboard',
    category: 'infrastructure',
    icon: 'globe-2',
    color: '#24a1c1',
    description: 'Dashboard web del router perimetral nativo de la nube y balanceador de carga.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'caddy',
    name: 'Caddy Web Portal',
    category: 'infrastructure',
    icon: 'globe',
    color: '#22b573',
    description: 'Servidor web y proxy inverso moderno y de alto rendimiento con HTTPS automático.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'pihole',
    name: 'Pi-hole Admin',
    category: 'infrastructure',
    icon: 'shield-check',
    color: '#96060c',
    description: 'Consola web de servidor DNS con bloqueo de publicidad y telemetría de red.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'adguard',
    name: 'AdGuard Home',
    category: 'infrastructure',
    icon: 'shield-check',
    color: '#68bc71',
    description: 'Panel web de servidor DNS con filtrado de contenido y control parental.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'wireguard',
    name: 'WireGuard Easy',
    category: 'infrastructure',
    icon: 'lock',
    color: '#8855ff',
    description: 'Interfaz web simplificada para gestión de clientes y túneles VPN WireGuard.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'firezone',
    name: 'Firezone',
    category: 'infrastructure',
    icon: 'shield-check',
    color: '#e056fd',
    description: 'Portal web de acceso seguro Zero-Trust (ZTNA) y VPN basada en WireGuard.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'openvpn',
    name: 'OpenVPN Access Server',
    category: 'infrastructure',
    icon: 'lock',
    color: '#ea6036',
    description: 'Portal web oficial de administración y cliente de conexión para OpenVPN empresarial.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'tailscale',
    name: 'Tailscale Admin',
    category: 'infrastructure',
    icon: 'shield',
    color: '#4f46e5',
    description: 'Consola web de administración de red mesh VPN privada basada en WireGuard.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'netbird',
    name: 'NetBird Dashboard',
    category: 'infrastructure',
    icon: 'shield-check',
    color: '#00a3ff',
    description: 'Panel web de gestión de red mesh VPN P2P con autenticación SSO y reglas ACL.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'headscale',
    name: 'Headscale Web UI',
    category: 'infrastructure',
    icon: 'server',
    color: '#34495e',
    description: 'Panel web de control autohospedado para servidor Tailscale / Headscale.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'unifi',
    name: 'UniFi Network',
    category: 'infrastructure',
    icon: 'radio',
    color: '#006fff',
    description: 'Controlador web de red, switches, gateways y puntos de acceso Ubiquiti.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'omada',
    name: 'TP-Link Omada Controller',
    category: 'infrastructure',
    icon: 'radio',
    color: '#00b0ff',
    description: 'Controlador web para gestión centralizada de switches, routers y puntos de acceso Omada.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'guacamole',
    name: 'Apache Guacamole',
    category: 'infrastructure',
    icon: 'monitor',
    color: '#27ae60',
    description: 'Gateway web sin cliente para acceso remoto a escritorios RDP, VNC y terminales SSH.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'netbox',
    name: 'NetBox DCIM & IPAM',
    category: 'infrastructure',
    icon: 'server',
    color: '#00857c',
    description: 'Plataforma web de referencia para modelado y gestión de infraestructura de red e IPs.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'phpipam',
    name: 'phpIPAM',
    category: 'infrastructure',
    icon: 'server',
    color: '#16a085',
    description: 'Gestor web de direcciones IP, subredes, VLANs, VRF y dispositivos de red.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'speedtest',
    name: 'Speedtest Tracker',
    category: 'infrastructure',
    icon: 'bar-chart',
    color: '#e67e22',
    description: 'Monitor web autohospedado que ejecuta pruebas de velocidad de internet periódicas con gráficos.',
    defaultCategoryName: 'Infraestructura',
  },
  {
    id: 'rustdesk',
    name: 'RustDesk Web Console',
    category: 'infrastructure',
    icon: 'monitor',
    color: '#ff6600',
    description: 'Consola web autohospedada de escritorio remoto y administración de sesiones.',
    defaultCategoryName: 'Infraestructura',
  },

  // ── Monitoreo & Observabilidad (Web Dashboards) ──────────────────────────
  {
    id: 'grafana',
    name: 'Grafana',
    category: 'monitoring',
    icon: 'bar-chart-2',
    color: '#f46800',
    description: 'Dashboards web interactivos y visualización de métricas y observabilidad.',
    defaultCategoryName: 'Monitoreo',
  },
  {
    id: 'prometheus',
    name: 'Prometheus',
    category: 'monitoring',
    icon: 'activity',
    color: '#e6522c',
    description: 'Consola web y base de datos time-series para consultas de métricas y alertas.',
    defaultCategoryName: 'Monitoreo',
  },
  {
    id: 'uptime-kuma',
    name: 'Uptime Kuma',
    category: 'monitoring',
    icon: 'check-circle',
    color: '#5cdd8b',
    description: 'Panel web de monitoreo de estado y páginas de status públicas/privadas.',
    defaultCategoryName: 'Monitoreo',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    category: 'monitoring',
    icon: 'alert-triangle',
    color: '#362d59',
    description: 'Plataforma web de seguimiento de errores y rendimiento en producción.',
    defaultCategoryName: 'Monitoreo',
  },
  {
    id: 'netdata',
    name: 'Netdata',
    category: 'monitoring',
    icon: 'bar-chart',
    color: '#00ab84',
    description: 'Dashboard web de monitoreo de infraestructura y métricas de servidor en tiempo real.',
    defaultCategoryName: 'Monitoreo',
  },
  {
    id: 'glances',
    name: 'Glances Web',
    category: 'monitoring',
    icon: 'pie-chart',
    color: '#0284c7',
    description: 'Visor web liviano de recursos de CPU, memoria, red y disco del host.',
    defaultCategoryName: 'Monitoreo',
  },
  {
    id: 'zabbix',
    name: 'Zabbix Web Frontend',
    category: 'monitoring',
    icon: 'shield-check',
    color: '#d32f2f',
    description: 'Consola web enterprise para monitoreo de redes, servidores y aplicaciones.',
    defaultCategoryName: 'Monitoreo',
  },
  {
    id: 'dozzle',
    name: 'Dozzle',
    category: 'monitoring',
    icon: 'terminal',
    color: '#f59e0b',
    description: 'Visor web de logs de contenedores Docker en tiempo real con búsqueda.',
    defaultCategoryName: 'Monitoreo',
  },
  {
    id: 'beszel',
    name: 'Beszel',
    category: 'monitoring',
    icon: 'activity',
    color: '#10b981',
    description: 'Panel web de monitoreo de servidores y contenedores ultra-liviano.',
    defaultCategoryName: 'Monitoreo',
  },
  {
    id: 'librenms',
    name: 'LibreNMS',
    category: 'monitoring',
    icon: 'bar-chart-2',
    color: '#e74c3c',
    description: 'Sistema web de monitoreo de red con autodetección SNMP y topología.',
    defaultCategoryName: 'Monitoreo',
  },

  // ── Almacenamiento & Archivos (Web Consoles) ─────────────────────────────
  {
    id: 'nextcloud',
    name: 'Nextcloud',
    category: 'storage',
    icon: 'cloud',
    color: '#0082c9',
    description: 'Portal web de almacenamiento de archivos en la nube, calendario y contactos.',
    defaultCategoryName: 'Archivos',
  },
  {
    id: 'syncthing',
    name: 'Syncthing Web GUI',
    category: 'storage',
    icon: 'folder-open',
    color: '#1676ac',
    description: 'Interfaz web para sincronización continua de carpetas P2P y dispositivos.',
    defaultCategoryName: 'Archivos',
  },
  {
    id: 'minio',
    name: 'MinIO Console',
    category: 'storage',
    icon: 'box',
    color: '#c72c48',
    description: 'Consola web para almacenamiento de objetos compatible con Amazon S3.',
    defaultCategoryName: 'Archivos',
  },
  {
    id: 'filebrowser',
    name: 'FileBrowser',
    category: 'storage',
    icon: 'folder',
    color: '#29b6f6',
    description: 'Administrador web de archivos simple y elegante para tu servidor.',
    defaultCategoryName: 'Archivos',
  },
  {
    id: 'seafile',
    name: 'Seafile Web',
    category: 'storage',
    icon: 'cloud',
    color: '#ff8c00',
    description: 'Portal web de almacenamiento en la nube con sincronización confiable.',
    defaultCategoryName: 'Archivos',
  },

  // ── Seguridad & Autenticación (Web Portals) ──────────────────────────────
  {
    id: 'vaultwarden',
    name: 'Vaultwarden',
    category: 'security',
    icon: 'shield',
    color: '#175ddc',
    description: 'Bóveda web de contraseñas Bitwarden compatible autohospedada.',
    defaultCategoryName: 'Seguridad',
  },
  {
    id: 'keycloak',
    name: 'Keycloak Admin Console',
    category: 'security',
    icon: 'key',
    color: '#4a90e2',
    description: 'Consola web de gestión de identidad y acceso (IAM) con OpenID Connect y SAML.',
    defaultCategoryName: 'Seguridad',
  },
  {
    id: 'authentik',
    name: 'Authentik',
    category: 'security',
    icon: 'lock',
    color: '#fd4b2d',
    description: 'Portal web de identidad OpenID Connect y SAML con flujos visuales.',
    defaultCategoryName: 'Seguridad',
  },
  {
    id: 'authelia',
    name: 'Authelia',
    category: 'security',
    icon: 'shield-check',
    color: '#1a56db',
    description: 'Portal web de autenticación y 2FA ligero para proxies inversos.',
    defaultCategoryName: 'Seguridad',
  },
  {
    id: 'wazuh',
    name: 'Wazuh Dashboard',
    category: 'security',
    icon: 'shield-check',
    color: '#00a4e4',
    description: 'Plataforma web de ciberseguridad, detección de amenazas, SIEM y monitoreo de integridad.',
    defaultCategoryName: 'Seguridad',
  },
  {
    id: 'crowdsec',
    name: 'CrowdSec Console',
    category: 'security',
    icon: 'shield',
    color: '#ff4757',
    description: 'Sistema colaborativo de detección de intrusiones, prevención y bloqueo de IPs maliciosas.',
    defaultCategoryName: 'Seguridad',
  },

  // ── Multimedia & Streaming (Web Clients & Servidores) ────────────────────
  {
    id: 'jellyfin',
    name: 'Jellyfin',
    category: 'media',
    icon: 'film',
    color: '#aa5cc3',
    description: 'Reproductor y servidor web multimedia para películas, series y música.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'plex',
    name: 'Plex Web',
    category: 'media',
    icon: 'play-circle',
    color: '#e5a00d',
    description: 'Media server y reproductor web de streaming para contenido personal.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'emby',
    name: 'Emby Web',
    category: 'media',
    icon: 'play-circle',
    color: '#52b043',
    description: 'Portal web de medios para organizar y reproducir video y música.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'audiobookshelf',
    name: 'Audiobookshelf',
    category: 'media',
    icon: 'mic',
    color: '#9b51e0',
    description: 'Reproductor y servidor web de audiolibros y podcasts con sincronización.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'immich',
    name: 'Immich Web',
    category: 'media',
    icon: 'image',
    color: '#4285f4',
    description: 'Galería web de fotos y videos con respaldo automático y búsqueda por IA.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'photoprism',
    name: 'PhotoPrism',
    category: 'media',
    icon: 'image',
    color: '#3498db',
    description: 'Galería web de fotos impulsada por IA con reconocimiento facial y mapas.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'navidrome',
    name: 'Navidrome',
    category: 'media',
    icon: 'music',
    color: '#e67e22',
    description: 'Reproductor web de música y streaming personal compatible con Subsonic.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'funkwhale',
    name: 'Funkwhale',
    category: 'media',
    icon: 'music',
    color: '#ff6b81',
    description: 'Plataforma web libre y federada para streaming y biblioteca de audio/música.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'kavita',
    name: 'Kavita Web Reader',
    category: 'media',
    icon: 'book-open',
    color: '#27ae60',
    description: 'Lector web y biblioteca digital de cómics, mangas y libros electrónicos.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'komga',
    name: 'Komga',
    category: 'media',
    icon: 'book-open',
    color: '#34495e',
    description: 'Servidor y lector web de cómics, mangas, BDs y revistas con soporte de múltiples usuarios.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'calibre-web',
    name: 'Calibre-Web',
    category: 'media',
    icon: 'book-open',
    color: '#e74c3c',
    description: 'Interfaz web limpia para explorar y leer libros de tu biblioteca Calibre.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'tubearchivist',
    name: 'TubeArchivist',
    category: 'media',
    icon: 'film',
    color: '#ff0000',
    description: 'Sistema web de indexación y archivo offline de canales y videos de YouTube.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'metube',
    name: 'MeTube',
    category: 'media',
    icon: 'download',
    color: '#e74c3c',
    description: 'Interfaz web para descarga de videos y audios desde YouTube y cientos de sitios vía yt-dlp.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'invidious',
    name: 'Invidious',
    category: 'media',
    icon: 'film',
    color: '#6c5ce7',
    description: 'Frontend web alternativo, privado y sin publicidad para explorar y reproducir YouTube.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'romm',
    name: 'RomM',
    category: 'media',
    icon: 'play-circle',
    color: '#6c5ce7',
    description: 'Administrador y explorador web de bibliotecas de videojuegos retro (ROMs) estilo Netflix.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'tautulli',
    name: 'Tautulli',
    category: 'media',
    icon: 'activity',
    color: '#e5a00d',
    description: 'Panel web de estadísticas, monitoreo de transmisiones y actividad de usuarios para Plex.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'sonarr',
    name: 'Sonarr',
    category: 'media',
    icon: 'download',
    color: '#00c4cc',
    description: 'Panel web de gestión automatizada de descargas y biblioteca de series.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'radarr',
    name: 'Radarr',
    category: 'media',
    icon: 'download',
    color: '#ffc230',
    description: 'Panel web de gestión automatizada de descargas y biblioteca de películas.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'lidarr',
    name: 'Lidarr',
    category: 'media',
    icon: 'music',
    color: '#16a085',
    description: 'Panel web de gestión automatizada de descargas de música y discografías.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'bazarr',
    name: 'Bazarr',
    category: 'media',
    icon: 'file-text',
    color: '#3498db',
    description: 'Administrador web para búsqueda y descarga automática de subtítulos para Sonarr y Radarr.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'prowlarr',
    name: 'Prowlarr',
    category: 'media',
    icon: 'search',
    color: '#ff5c5c',
    description: 'Consola web de gestión de indexadores Torrent y Usenet para la suite *arr.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'jellyseerr',
    name: 'Jellyseerr / Overseerr',
    category: 'media',
    icon: 'film',
    color: '#8b5cf6',
    description: 'Portal web de solicitudes y descubrimiento de medios para Jellyfin y Plex.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'qbittorrent',
    name: 'qBittorrent Web UI',
    category: 'media',
    icon: 'download',
    color: '#2f679f',
    description: 'Cliente BitTorrent con panel web de control remoto.',
    defaultCategoryName: 'Multimedia',
  },
  {
    id: 'transmission',
    name: 'Transmission Web UI',
    category: 'media',
    icon: 'download',
    color: '#c0392b',
    description: 'Panel web para cliente de descargas BitTorrent ligero y eficiente.',
    defaultCategoryName: 'Multimedia',
  },

  // ── Comunicación & Chat (Plataformas Web) ────────────────────────────────
  {
    id: 'mattermost',
    name: 'Mattermost',
    category: 'communication',
    icon: 'message-square',
    color: '#0058cc',
    description: 'Chat web para equipos y mensajería en tiempo real.',
    defaultCategoryName: 'Comunicación',
  },
  {
    id: 'element',
    name: 'Element / Matrix',
    category: 'communication',
    icon: 'chat',
    color: '#0dbd8b',
    description: 'Cliente web de mensajería descentralizada y encriptada de extremo a extremo.',
    defaultCategoryName: 'Comunicación',
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'communication',
    icon: 'slack',
    color: '#4a154b',
    description: 'Espacio de trabajo web para comunicación y canales de equipo.',
    defaultCategoryName: 'Comunicación',
  },
  {
    id: 'mailcow',
    name: 'Mailcow Webmail',
    category: 'communication',
    icon: 'mail',
    color: '#2c3e50',
    description: 'Panel web de administración de correo y webmail SOGo autohospedado.',
    defaultCategoryName: 'Comunicación',
  },
  {
    id: 'zulip',
    name: 'Zulip',
    category: 'communication',
    icon: 'message-square',
    color: '#6492fe',
    description: 'Chat web para equipos organizado por hilos y canales estructurados.',
    defaultCategoryName: 'Comunicación',
  },
  {
    id: 'rocketchat',
    name: 'Rocket.Chat',
    category: 'communication',
    icon: 'chat',
    color: '#f5455c',
    description: 'Plataforma web de comunicación omnicanal y colaboración segura.',
    defaultCategoryName: 'Comunicación',
  },

  // ── Productividad, Agendamiento & Documentación ──────────────────────────
  {
    id: 'calcom',
    name: 'Cal.com',
    category: 'productivity',
    icon: 'clock',
    color: '#222222',
    description: 'Plataforma web de agendamiento y reserva de citas y reuniones (alternativa de código abierto a Calendly).',
    defaultCategoryName: 'Productividad',
  },
  {
    id: 'excalidraw',
    name: 'Excalidraw',
    category: 'productivity',
    icon: 'edit-3',
    color: '#6965db',
    description: 'Pizarra virtual web colaborativa y diagramación libre estilo boceto.',
    defaultCategoryName: 'Productividad',
  },
  {
    id: 'wikijs',
    name: 'Wiki.js',
    category: 'documentation',
    icon: 'book-open',
    color: '#1976d2',
    description: 'Plataforma web de documentación y wiki modular moderna para equipos.',
    defaultCategoryName: 'Documentación',
  },
  {
    id: 'hedgedoc',
    name: 'HedgeDoc',
    category: 'documentation',
    icon: 'file-text',
    color: '#333333',
    description: 'Editor colaborativo web de notas markdown en tiempo real.',
    defaultCategoryName: 'Documentación',
  },
  {
    id: 'paperless',
    name: 'Paperless-ngx',
    category: 'productivity',
    icon: 'file-text',
    color: '#107c41',
    description: 'Panel web de gestión documental y digitalización de archivos con OCR.',
    defaultCategoryName: 'Productividad',
  },
  {
    id: 'stirling-pdf',
    name: 'Stirling-PDF',
    category: 'productivity',
    icon: 'file',
    color: '#e11d48',
    description: 'Suite web completa para editar, unir, dividir y convertir archivos PDF.',
    defaultCategoryName: 'Productividad',
  },
  {
    id: 'linkwarden',
    name: 'Linkwarden',
    category: 'productivity',
    icon: 'link',
    color: '#059669',
    description: 'Gestor web de marcadores y lectura offline con captura automática de páginas.',
    defaultCategoryName: 'Productividad',
  },
  {
    id: 'it-tools',
    name: 'IT-Tools',
    category: 'productivity',
    icon: 'code-2',
    color: '#3b82f6',
    description: 'Colección web de utilidades y convertidores para desarrolladores.',
    defaultCategoryName: 'Productividad',
  },
  {
    id: 'drawio',
    name: 'Draw.io',
    category: 'productivity',
    icon: 'edit-3',
    color: '#f08705',
    description: 'Editor web de diagramas de flujo, arquitectura y wireframes.',
    defaultCategoryName: 'Productividad',
  },
  {
    id: 'penpot',
    name: 'Penpot',
    category: 'productivity',
    icon: 'layers',
    color: '#8e44ad',
    description: 'Diseño de interfaces UI/UX web colaborativo open-source (alternativa a Figma).',
    defaultCategoryName: 'Productividad',
  },
  {
    id: 'trilium',
    name: 'Trilium Notes',
    category: 'productivity',
    icon: 'file-text',
    color: '#2b579a',
    description: 'Organizador web de notas jerárquicas con cifrado y árbol de conocimiento.',
    defaultCategoryName: 'Productividad',
  },
  {
    id: 'focalboard',
    name: 'Focalboard',
    category: 'productivity',
    icon: 'check-square',
    color: '#1d89d4',
    description: 'Gestión web de proyectos y tareas estilo Kanban (alternativa a Trello/Notion).',
    defaultCategoryName: 'Productividad',
  },
  {
    id: 'vikunja',
    name: 'Vikunja',
    category: 'productivity',
    icon: 'check-square',
    color: '#1992d4',
    description: 'Gestor web de tareas y listas de pendientes con vistas de lista, tabla y kanban.',
    defaultCategoryName: 'Productividad',
  },
  {
    id: 'wallabag',
    name: 'Wallabag',
    category: 'productivity',
    icon: 'bookmark',
    color: '#9b59b6',
    description: 'Aplicación web de lectura diferida (Read-it-later) para artículos y páginas web.',
    defaultCategoryName: 'Productividad',
  },

  // ── Domótica, Impresión 3D, Finanzas & Hogar ─────────────────────────────
  {
    id: 'home-assistant',
    name: 'Home Assistant',
    category: 'iot',
    icon: 'home',
    color: '#03a9f4',
    description: 'Panel web de control y automatización integral del hogar enfocado en privacidad.',
    defaultCategoryName: 'Domótica',
  },
  {
    id: 'node-red',
    name: 'Node-RED',
    category: 'iot',
    icon: 'zap',
    color: '#8f0000',
    description: 'Entorno de programación visual basado en flujos para conectar dispositivos IoT, APIs y servicios online.',
    defaultCategoryName: 'Domótica',
  },
  {
    id: 'zigbee2mqtt',
    name: 'Zigbee2MQTT Web Frontend',
    category: 'iot',
    icon: 'radio',
    color: '#ffb300',
    description: 'Panel web de administración de dispositivos Zigbee y mapas de red.',
    defaultCategoryName: 'Domótica',
  },
  {
    id: 'frigate',
    name: 'Frigate NVR',
    category: 'iot',
    icon: 'camera',
    color: '#2ecc71',
    description: 'Visor web NVR para cámaras con detección de objetos y personas por IA.',
    defaultCategoryName: 'Domótica',
  },
  {
    id: 'scrypted',
    name: 'Scrypted Management Console',
    category: 'iot',
    icon: 'camera',
    color: '#00d2d3',
    description: 'Consola web de integración de cámaras de alta velocidad y video en streaming.',
    defaultCategoryName: 'Domótica',
  },
  {
    id: 'octoprint',
    name: 'OctoPrint',
    category: 'iot',
    icon: 'monitor',
    color: '#008000',
    description: 'Servidor web para control remoto, monitoreo por cámara y gestión de impresiones 3D.',
    defaultCategoryName: 'Impresión 3D',
  },
  {
    id: 'mainsail',
    name: 'Mainsail / Fluidd',
    category: 'iot',
    icon: 'monitor',
    color: '#0099ff',
    description: 'Interfaz web moderna y reactiva para impresoras 3D con firmware Klipper.',
    defaultCategoryName: 'Impresión 3D',
  },
  {
    id: 'mealie',
    name: 'Mealie',
    category: 'lifestyle',
    icon: 'coffee',
    color: '#e58e26',
    description: 'Aplicación web de recetas de cocina y planificación de comidas familiar.',
    defaultCategoryName: 'Utilidades',
  },
  {
    id: 'grocy',
    name: 'Grocy',
    category: 'lifestyle',
    icon: 'package',
    color: '#708090',
    description: 'Aplicación web de gestión de inventario de despensa y compras del hogar.',
    defaultCategoryName: 'Utilidades',
  },
  {
    id: 'firefly',
    name: 'Firefly III',
    category: 'finance',
    icon: 'credit-card',
    color: '#27ae60',
    description: 'Panel web de finanzas personales, gestión de presupuestos y gastos.',
    defaultCategoryName: 'Finanzas',
  },
  {
    id: 'actualbudget',
    name: 'Actual Budget',
    category: 'finance',
    icon: 'dollar-sign',
    color: '#805ad5',
    description: 'Aplicación web de presupuestación personal basada en el método zero-based.',
    defaultCategoryName: 'Finanzas',
  },
  {
    id: 'wallos',
    name: 'Wallos',
    category: 'finance',
    icon: 'credit-card',
    color: '#38a169',
    description: 'Panel web para rastreo de suscripciones, pagos recurrentes y gastos fijos.',
    defaultCategoryName: 'Finanzas',
  },
];
